export const aiScopes = [
  "mail.read",
  "mail.write",
  "mail.send",
  "mail.bulk_write",
  "calendar.read",
  "calendar.write",
  "contacts.read",
  "contacts.write",
  "templates.read",
  "templates.write",
  "signatures.read",
  "signatures.write",
  "files.read",
  "files.write",
  "images.generate",
  "campaign.read",
  "campaign.write",
  "campaign.send",
  "research.use",
  "automations.read",
  "automations.write",
  "tasks.read",
  "tasks.write",
  "settings.read",
  "settings.write",
  "workspace.read",
  "workspace.admin",
  "domain.read",
  "domain.write",
  "alias.read",
  "alias.write",
  "mailbox_admin.read",
  "mailbox_admin.write",
  "admin.health.read",
  "admin.audit.read",
] as const;

export type AiScope = (typeof aiScopes)[number];

export type ConfirmationPolicy = "never" | "contextual" | "always";

export const scopeConfirmationPolicy: Record<AiScope, ConfirmationPolicy> = {
  "mail.read": "never",
  "mail.write": "never",
  "mail.send": "always",
  "mail.bulk_write": "contextual",
  "calendar.read": "never",
  "calendar.write": "contextual",
  "contacts.read": "never",
  "contacts.write": "contextual",
  "templates.read": "never",
  "templates.write": "contextual",
  "signatures.read": "never",
  "signatures.write": "contextual",
  "files.read": "never",
  "files.write": "contextual",
  "images.generate": "contextual",
  "campaign.read": "never",
  "campaign.write": "contextual",
  "campaign.send": "always",
  "research.use": "never",
  "automations.read": "never",
  "automations.write": "always",
  "tasks.read": "never",
  "tasks.write": "never",
  "settings.read": "never",
  "settings.write": "contextual",
  "workspace.read": "never",
  "workspace.admin": "always",
  "domain.read": "never",
  "domain.write": "always",
  "alias.read": "never",
  "alias.write": "always",
  "mailbox_admin.read": "never",
  "mailbox_admin.write": "always",
  "admin.health.read": "never",
  "admin.audit.read": "never",
};

export const isAiScope = (value: string): value is AiScope =>
  (aiScopes as readonly string[]).includes(value);
