import { useEffect, useState } from "react";
import { completeMailboxSetup, getAccountContext, requestMailboxSetup, type AccountContext } from "../auth";
import { logout } from "../auth";
import { AuthCard } from "../components/auth/AuthCard";
import { AuthPage } from "../components/auth/AuthPage";
import { BrandMark } from "../components/auth/BrandMark";

export function ControlCenterPage() {
  const [context, setContext] = useState<AccountContext | null>(null);
  const [setupMailbox, setSetupMailbox] = useState<AccountContext["managedMailboxes"][number] | null>(null);
  const [setupCode, setSetupCode] = useState("");
  const [setupPassword, setSetupPassword] = useState("");
  const [setupConfirm, setSetupConfirm] = useState("");
  const [setupMessage, setSetupMessage] = useState("");
  useEffect(() => { void getAccountContext().then(setContext).catch(() => undefined); }, []);
  if (!context) return <AuthPage><AuthCard><p className="gsw-login-hint">Loading your control center…</p></AuthCard></AuthPage>;
  const workspace = context.workspaceMemberships[0];
  const domains = new Set(context.mailboxMemberships.map((mailbox) => mailbox.domain));
  const startMailboxSetup = async (mailbox: AccountContext["managedMailboxes"][number]) => { try { await requestMailboxSetup(mailbox.id); setSetupMailbox(mailbox); setSetupMessage(`A setup code was sent to ${context.user.email}.`); } catch (error) { setSetupMessage(error instanceof Error ? error.message : "Could not send setup code."); } };
  const finishMailboxSetup = async () => { if (!setupMailbox) return; if (setupCode.length !== 6 || setupPassword.length < 8 || setupPassword !== setupConfirm) { setSetupMessage("Enter the 6-digit code and matching password of at least 8 characters."); return; } try { await completeMailboxSetup(setupMailbox.id, setupCode, setupPassword); setSetupMessage(`${setupMailbox.address} login is ready. Sign in with its address and new password.`); setContext(await getAccountContext()); setSetupMailbox(null); } catch (error) { setSetupMessage(error instanceof Error ? error.message : "Could not finish mailbox setup."); } };
  return <main className="gsw-control-center">
    <aside className="gsw-control-nav"><BrandMark size={54} /><p className="gsw-setup-kicker">GSW Admin</p><h1>{workspace?.name ?? "Workspace"}</h1><nav><a className="is-active" href="/control-center">Overview</a><a href="/setup">Domains</a><a href="/setup">Mailboxes</a><a href="/setup">Users</a><a href="/setup">Admins</a><a href="/setup">Billing</a><a href="/setup">Security</a><a href="/setup">Settings</a></nav><button className="gsw-btn gsw-btn-ghost" onClick={() => void logout()}>Sign out</button></aside>
    <section className="gsw-control-main"><header><div><p className="gsw-setup-kicker">Control center</p><h2>{workspace?.name ?? "Guided Steps Wellness"}</h2><p>{workspace?.role ?? "member"} · {context.user.email}</p></div><button className="gsw-btn gsw-btn-primary" onClick={() => window.location.assign("/mail")}>Open Mail</button></header><div className="gsw-control-stats"><div><strong>{domains.size}</strong><span>Domains</span></div><div><strong>{context.managedMailboxes.length}</strong><span>Mailboxes</span></div><div><strong>{context.workspaceMemberships.length}</strong><span>Workspaces</span></div></div><div className="gsw-control-grid"><article><h3>Domains</h3><p>{domains.size ? [...domains].join(" · ") : "No domains connected"}</p><span className="gsw-status-pill">{domains.size ? "Connected" : "Needs setup"}</span></article><article><h3>Mailboxes</h3>{context.managedMailboxes.length ? context.managedMailboxes.map((mailbox) => <div className="gsw-managed-mailbox" key={mailbox.id}><p>{mailbox.address}<br /><small>{mailbox.authSetupStatus === "ready" ? "Login ready" : "Login setup required"}</small></p>{mailbox.authSetupStatus === "pending" && <button className="gsw-btn gsw-btn-quiet" onClick={() => void startMailboxSetup(mailbox)}>Set up login</button>}</div>) : <p>No mailboxes connected</p>}<span className="gsw-status-pill">{context.managedMailboxes.some((mailbox) => mailbox.authSetupStatus === "pending") ? "Setup required" : "Active"}</span></article><article><h3>Setup</h3><p>{context.onboardingComplete ? "Existing installation adopted" : "Workspace setup needs attention"}</p><span className="gsw-status-pill">{context.onboardingComplete ? "Complete" : "In progress"}</span></article><article><h3>Mailbox access</h3><p>{context.mailboxMemberships.length ? "Explicit memberships only" : "No mailbox content access"}</p><span className="gsw-status-pill">Secure</span></article></div>{setupMessage && <p className="gsw-login-hint">{setupMessage}</p>}{setupMailbox && <div className="gsw-setup-inline"><h3>Set up {setupMailbox.address}</h3><label className="gsw-auth-field">Setup code<input inputMode="numeric" maxLength={6} value={setupCode} onChange={(event) => setSetupCode(event.target.value.replace(/\D/g, "").slice(0, 6))} /></label><label className="gsw-auth-field">New password<input type="password" value={setupPassword} onChange={(event) => setSetupPassword(event.target.value)} /></label><label className="gsw-auth-field">Confirm password<input type="password" value={setupConfirm} onChange={(event) => setSetupConfirm(event.target.value)} /></label><button className="gsw-btn gsw-btn-primary" onClick={() => void finishMailboxSetup()}>Finish setup</button></div>}</section>
  </main>;
}
